### ISSUE TITLE
Use environment variables, not a potentially public Java script

### ISSUE THREAD

**Issue by ghost** [pavog/Multicraft-api#2]
@pavog Update documentation to use system environment variables:

```java
String testApiUrl = "https://panel.testurl.com/api.php";
String testApiUsername = System.getenv("MULTICRAFT_USER");
String testApiKey = System.getenv("MULTICRAFT_KEY");
MulticraftAPI api = new MulticraftAPI(testApiUrl, testApiUsername, testApiKey);
```

Would prevent people from leaking their secret token, email and potentiallly losing their world.
Not that I've done so, but the Minecraft community isnt necessarily very code or security-savvy.

**Comment by pavog** [comment]
Hi, I would like to keep my getting started guide simple and short: It is supposed to contain only 3 variables that will be inserted into the new Multicraft Api object.
I think that a developer implementing this api knows that he can set the values of the variables in the code, get them from a configuration or from system variables.

Also: I'm not sure why this method should be used instead of placing the URL, username and API key directly in the code, since the code is not public but runs on your server in your application, for example in a plugin. In my opinion, it makes no difference whether the data is in the code or in environment variables.

Just to clarify: I am not against your suggestion, but I think a developer should know how to fill the variables with values, and I would like to keep the readme/instructions short and simple to make it easier to get started.

**Comment by ghost** [comment]
Alright, understood and I hope this issue provides guidance on using secret env vars for CI.
